version: "3.3"

services:
  v2ray:
    container_name: v2ray
    restart: always
    image: teddysun/xray
    environment: 
      - xray.vmess.aead.forced=true
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    networks:
      - v2ray-network
    logging:
      driver: "json-file"
      options:
        max-size: 5m

  nginx-v2ray:
    container_name: nginx-v2ray
    restart: always
    image: nginx:1.23.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/:/ssl/:ro
    ports:
      - 443:443
      - 80:80
    networks:
      - v2ray-network
    logging:
      driver: "json-file"
      options:
        max-size: 5m

networks:
  v2ray-network:
    external: True
