version: "3.3"

services:
  v2ray:
    container_name: v2ray
    restart: always
    image: teddysun/xray
    ports:
      - 80:80
    environment: 
       - xray.vmess.aead.forced=true
    volumes:
      - ./config.json:/etc/xray/config.json:ro
    logging:
      driver: "json-file"
      options:
        max-size: 5m
